/**
 * Generates the country option list consumed by the Decap CMS admin widgets
 * (public/admin/country-widget.js).
 *
 * Single source of truth: the SAME i18n-iso-countries English names that
 * src/lib/country-codes.ts resolves tags against. Keeping the editor's picklist
 * and the runtime resolver on one source means any name an editor can pick is a
 * name the map/flag resolver recognises.
 *
 * Output is a plain <script>-includable file that sets window.COUNTRY_OPTIONS,
 * so the static admin (no bundler) can read it without a fetch.
 *
 * Run via the `prebuild` npm script; the generated file is also committed so
 * `next dev` works without a manual build step.
 */
import { writeFileSync } from "fs";
import path from "path";
import countries from "i18n-iso-countries";
import en from "i18n-iso-countries/langs/en.json";

countries.registerLocale(en);

// "Europe" is a supported special value in country-codes.ts (SPECIAL_ALPHA2).
const SPECIAL = ["Europe"];

const names = Object.values(countries.getNames("en"));
const options = Array.from(new Set([...SPECIAL, ...names])).sort((a, b) =>
  a.localeCompare(b)
);

const out =
  `// AUTO-GENERATED by scripts/generate-country-options.ts — do not edit by hand.\n` +
  `window.COUNTRY_OPTIONS = ${JSON.stringify(options, null, 2)};\n`;

const target = path.join(process.cwd(), "public/admin/country-options.js");
writeFileSync(target, out);
console.log(`Wrote ${options.length} country options to ${target}`);
