/**
 * Generates the language option list consumed by the Decap CMS admin widget
 * (public/admin/language-widget.js) for the commission name "Language Code"
 * field (name.translations[].language).
 *
 * The field stores an ISO 639-1 code (e.g. "en", "de"). The runtime matches it
 * exactly and case-sensitively (`t.language === "en"`) to surface the English
 * name, so a free-text typo ("EN", "english", "deu") silently breaks name
 * resolution. Constraining the editor to this generated picklist keeps the
 * stored value a clean code while still showing a searchable language name.
 *
 * Names come from Intl.DisplayNames so the editor sees "German (de)" but the
 * stored value stays "de". Output is a plain <script>-includable file that sets
 * window.LANGUAGE_OPTIONS, so the static admin (no bundler) can read it without
 * a fetch.
 *
 * Run via the `prebuild` npm script; the generated file is also committed so
 * `next dev` works without a manual build step.
 */
import { writeFileSync } from "fs";
import path from "path";

// The full ISO 639-1 set. Names are derived at generation time, so this only
// needs the codes — the single source of truth for which languages exist.
const ISO_639_1 = [
  "aa", "ab", "ae", "af", "ak", "am", "an", "ar", "as", "av", "ay", "az",
  "ba", "be", "bg", "bi", "bm", "bn", "bo", "br", "bs",
  "ca", "ce", "ch", "co", "cr", "cs", "cu", "cv", "cy",
  "da", "de", "dv", "dz",
  "ee", "el", "en", "eo", "es", "et", "eu",
  "fa", "ff", "fi", "fj", "fo", "fr", "fy",
  "ga", "gd", "gl", "gn", "gu", "gv",
  "ha", "he", "hi", "ho", "hr", "ht", "hu", "hy", "hz",
  "ia", "id", "ie", "ig", "ii", "ik", "io", "is", "it", "iu",
  "ja", "jv",
  "ka", "kg", "ki", "kj", "kk", "kl", "km", "kn", "ko", "kr", "ks", "ku", "kv", "kw", "ky",
  "la", "lb", "lg", "li", "ln", "lo", "lt", "lu", "lv",
  "mg", "mh", "mi", "mk", "ml", "mn", "mr", "ms", "mt", "my",
  "na", "nb", "nd", "ne", "ng", "nl", "nn", "no", "nr", "nv", "ny",
  "oc", "oj", "om", "or", "os",
  "pa", "pi", "pl", "ps", "pt",
  "qu",
  "rm", "rn", "ro", "ru", "rw",
  "sa", "sc", "sd", "se", "sg", "si", "sk", "sl", "sm", "sn", "so", "sq", "sr", "ss", "st", "su", "sv", "sw",
  "ta", "te", "tg", "th", "ti", "tk", "tl", "tn", "to", "tr", "ts", "tt", "tw", "ty",
  "ug", "uk", "ur", "uz",
  "ve", "vi", "vo",
  "wa", "wo",
  "xh",
  "yi", "yo",
  "za", "zh", "zu",
];

const displayNames = new Intl.DisplayNames(["en"], { type: "language" });

const options = ISO_639_1
  .map((code) => {
    const name = displayNames.of(code);
    // Intl returns the code unchanged when it has no name for it; drop those so
    // the picklist only offers codes that resolve to a human-readable language.
    return name && name !== code ? { code, name } : null;
  })
  .filter((o): o is { code: string; name: string } => o !== null)
  .sort((a, b) => a.name.localeCompare(b.name));

const out =
  `// AUTO-GENERATED by scripts/generate-language-options.ts — do not edit by hand.\n` +
  `window.LANGUAGE_OPTIONS = ${JSON.stringify(options, null, 2)};\n`;

const target = path.join(process.cwd(), "public/admin/language-options.js");
writeFileSync(target, out);
console.log(`Wrote ${options.length} language options to ${target}`);
