/**
 * Generates the country option list consumed by the TinaCMS country fields
 * (tina/fields.tsx).
 *
 * Single source of truth: the names come from src/lib/country-codes.ts itself,
 * so any name an editor can pick is by construction a name the flag and map
 * resolver recognises.
 *
 * They are common names — "Moldova", "South Korea", "Russia" — because that is
 * what the resolver now matches on. The list used to be the ISO register's
 * official names, which is how content ended up full of names the resolver could
 * not find: the picklist offered "Moldova, Republic of", editors typed "Moldova"
 * instead, and a fuzzy matcher was left to guess at the difference.
 *
 * Output is a small TS module the Tina config imports. Importing
 * country-codes.ts directly would work too, but it would bundle the whole
 * world-countries dataset into the admin for the sake of one list of names.
 *
 * Run via the `prebuild` npm script; the generated file is also committed so
 * `tinacms dev` works without a manual build step.
 */
import { writeFileSync } from "fs";
import path from "path";
import { allCountryNames } from "../src/lib/country-codes";

// "Europe" is a supported special value in country-codes.ts (SPECIAL_ALPHA2).
const SPECIAL = ["Europe"];

const options = Array.from(new Set([...SPECIAL, ...allCountryNames()])).sort(
  (a, b) => a.localeCompare(b)
);

const out =
  `// AUTO-GENERATED by scripts/generate-country-options.ts — do not edit by hand.\n` +
  `export const COUNTRY_OPTIONS: readonly string[] = ${JSON.stringify(options, null, 2)};\n`;

const target = path.join(process.cwd(), "tina/options/countries.ts");
writeFileSync(target, out);
console.log(`Wrote ${options.length} country options to ${target}`);
